-- MVP журнала изменений SKU.
-- SQL не подключается автоматически: выполните этот файл вручную в Supabase SQL Editor.
-- Таблица предназначена только для хранения и отображения изменений карточки, цены,
-- рекламы и поставок; текущие алгоритмы analytics/problems/Morning Brief не меняются.

create table if not exists public.change_log (
    id bigint generated by default as identity primary key,
    change_date date not null,
    seller_id bigint,
    seller_name text,
    nm_id bigint,
    vendor_code text,
    change_type text not null,
    old_value text,
    new_value text,
    changed_by text,
    comment text,
    created_at timestamptz default now()
);

comment on table public.change_log is 'MVP журнала изменений SKU для ручного связывания изменений с динамикой продаж.';
comment on column public.change_log.change_date is 'Дата фактического изменения.';
comment on column public.change_log.change_type is 'Тип изменения: карточка, цена, реклама, поставка или другой ручной тип.';
